config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'cloud_of_witnesses', to: 'pages#cloud_of_witnesses'
  get 'how_to', to: 'pages#how_to'

  get 'signup', to: 'users#new'
  resources :users, except: [:new, :show]
  resource :studies, except: [:show, :new]
  get 'study', to: 'studies#new'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/Study.rb
class Study < ActiveRecord::Base
	belongs_to :user
  validates :title, presence: true, allow_blank: false
  validates :summary, length: { maximum: 140 }
end

app/models/User.rb
class User < ActiveRecord::Base
	has_many :studies
	before_save { self.email = email.downcase }
	validates :username, presence: true, 
						length: { minimum: 3, maximum: 25}, 
						uniqueness: { case_sensitive: false }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates	:email, presence: true, length: { maximum: 105 },
						uniqueness: { case_sensitive: false },
						format: { with: VALID_EMAIL_REGEX }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_study, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		redirect_to study_path if logged_in?
	end

	def cloud_of_witnesses
		#show a random recording of saints shouting "Praise the Lord!"
	end

	def about
	end

	def how_to

	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "You have successfully logged in"
			redirect_to study_path
		else
			flash.now[:danger] = "There was something wrong with your login information"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path
	end
end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController

	def new
		require_user
		@user = current_user
		@study = Study.new
		@studies = Study.all.sort_by &:updated_at
	end

	def create
		@study = Study.new(study_params)
		@study.user = current_user
		if @study.save
			flash[:success] = "You made it!"
			redirect_to '/cloud_of_witnesses'
		else
			flash[:danger] = "Uh oh—something went wrong"
			redirect_to study_path
		end
	end

	def edit
	end

	def update
		@study = Study.find(session[:study_id])
		if @study.update_attributes(study_params)
			flash[:success] = "You made it!"
			#successful update
			redirect_to '/cloud_of_witnesses'
		else
			flash[:danger] = "Oh no! Your study could not be saved."
			render 'edit'
		end

	end

	def destroy
		@study = Study.find(params[:study_id])
		@study.destroy
		redirect_to study_path
	end

	private
	def study_params
		params.inspect
		params.require(:study).permit( :title, :summary, :user_id )
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :set_user, only: [:edit, :update, :show]
before_action :require_same_user, only: [:edit, :update, :destroy]
before_action :require_admin, only: [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) 
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Welcome to Take Time, #{@user.username}"
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:danger] = "User has been deleted"
    redirect_to root_path
  end
  
  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end
  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user and !current_user.admin?
      flash[:danger] = "You can only edit your own account"
      redirect_to root_path
    end
  end

  def require_admin
    if logged_in? and !current_user.admin?
      flash[:danger] = "Only admin users can perform that action"
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Take Time"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end

	def gravatar_for(user, options = { size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end

	def print_time(time)
		# the 12*60*60 is a shameless hack to use NZ timezone
		user_timezone = 12*60*60
		seconds = (Time.current + user_timezone).beginning_of_day - (time + user_timezone).beginning_of_day
		days = seconds.to_i / (24 * 60 * 60)

		case days
		when 0
			"today"
		when 1
			"yesterday"
		when 2..7
			time.strftime("%A")
		else
			days.to_s + " days ago"
		end
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
	<footer>
		<small>
		</small>
		<nav>
			<ul>
			</ul>
		</nav>
	</footer>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
		<div class='alert alert-<%="#{name}" %>'>
			<a href="#" class="close" data-dismiss="alert">&#215;</a>
			<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
		</div>
		<% end %>
	</div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Take Time", root_path, class: "navbar-brand", id: "logo"  %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if logged_in? || true %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-menu-hamburger" aria-hidden="true"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to 'How to Study', how_to_path %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">One more separated link</a></li>
            </ul>
          </li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.username %> <%= "(Admin)" if current_user.admin? %> <span class="caret"></span></a>
            <ul class="dropdown-menu blue-white">
              <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path, class: "white" %></li>
          <li><%= link_to 'Sign up', signup_path, class: "white" %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/navigation' %>
	<div class="container">
		<%= render 'layouts/messages' %>
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/cloud_of_witnesses.html.erb
<h1>Praise the Lord!</h1>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Take Time</h1>
	<%= link_to "Sign up now", signup_path, class: "btn btn-primary btn-large btn-xlarge" %>
</div>

app/views/pages/how_to.html.erb
<div class="readable-container"><h1>How to Study</h1>
<p>There are many ways to study the truth; none of them are wrong. Anything you do that brings Christ as the living Word into you is a wonderful thing! However, this site follows a particular method of study to guide you in digging deeply into the word, and into the ministry. The goal of these studies is threefold:</p>
<ul>
	<li>To spend time alone with the Lord, being infused by Him.</li>
	<li>To get the truth into you.</li>
	<li>To cause the truth to remain with you.</li>
</ul>
With these goals in view, this site guides you through the following steps in studying the truth:
<h2>Pray</h2>
Pray short prayers to open up to the Lord.
<h2>Sing</h2>
Sing a song to open to the Lord. This can be on the topic of studying the truth (Hymns #812 is a good one), or it can simply be any song that washes you and brings you to the Lord’s presence.
<h2>Pray-read</h2>
Pick a few verses from the section you will study, and thoroughly pray over them. A good way to pray-read is 1) Repeat the words directly, saying “amen!” 2) Apply the words to yourself, and pray to the Lord using the verses as the topic of your prayer. 3) Pray for others, using the verses as the topic of your prayer.
<h2>Study text with outlines</h2>
The outlines in the Recovery version are very important, they should direct your study. As you read through the text, try to find verses and phrases that link to the outline. As you study, feel free to underline, circle, highlight, and write notes next to the text. 
<h2>Study footnotes</h2>
Read through the footnotes, and try to find key phrases that relate to the verse. If you use multiple colors for your pens and highlighters, a good idea is to have one color per line of thought. Then any verses, footnotes, or notes that you write can all be done in the same color for that topic, and it will be very easy to link them visually.
<h2>Study Life-studies</h2>
Read through the life-studies related to the text, and look for any points not mentioned in the footnotes. Whenever you receive some light from the Lord, pray over it and add to the notes in your Bible.
<h2>Create key-point cards</h2>
After you study, write down a few key-points onto flashcards in a question-answer format. The key to flashcards is making them brief. For example, after studying the genealogy in Matthew 1, you may write the question “Who are the five women in Christ’s genealogy?” The answer might be simply “Tamar, Rahab, Ruth, Wife of Uriah, Mary.” Having a simple answer means it’s easier to remember. Don’t worry about all the details and significances. If you can remember the names, then probably you will remember all the details you enjoyed anyway! As a rule, just think when you are reviewing your flashcards: “Is this too difficult for me to remember?” If so, you may want to change the card, or discard it completely.
<h2>Create summary cards</h2>
Similar to the key-point cards, at the end of each chapter you study write a short summary of the events in the chapter. For example, for Matthew 1 write “Matthew 1” as the question, and the answer might be “Genealogy of Christ—proving His lineage as King. His origin—Begotten of the Holy Spirit, born of a virgin. His name—Jesus & Emmanuel.” This covers the three main points covered in chapter 1. Anything longer, and it will be too difficult to remember. The key to flashcards is short and simple!
headingReview
In order to remember and keep the word abiding in you, you must regularly review what you have studied. Since you have created question-based flashcards of key points and chapter summaries, the easiest way to review is to simply go through your flashcards, ask the questions and try to answer them from memory. You can do this with manual flashcards, or use software such as Anki or FlashCardsDeluxe to create electronic flashcards.
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h2 class="panel-title">
					<%= pluralize(obj.errors.count, "error") %>
					prohibited this article from being saved:
				</h2>
				<div class="panel-body">
					<ul>
						<% obj.errors.full_messages.each do |msg| %>
						<li> <%= msg %> </li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/studies/_form.html.erb
	<%= form_for(@study, class: "study-form") do |f| %>

  <%= f.text_field :title, class: "study-field study-title-field", placeholder: "What I did today..." %>
  <%= f.text_area :summary, id: "study-summary", class: "study-field study-summary-field", placeholder: "Summary..." %>

  <div id="word-count">140 characters</div>

  <%= f.submit class: "primary", value: "I took time today" %>
  <% end %>

app/views/studies/_ticker.html.erb
<div class="ticker-box">
  <div class="ticker-title">
    Recent Studies
  </div>
  <% @studies.reverse.each do |study| %>
  <div class="ticker-row">
    <div class="username">
      <%= study.user.username %>
    </div>
    <div class="ticker-study-summary">
      <%= study.summary if study.summary %>
    </div>
    <div class="ticker-study-title">
      <%= study.title %>
    </div>

    <div class="ticker-time">
      <%= print_time(study.created_at) %>
    </div>
  </div>
  <% end %>
</div>

app/views/studies/new.html.erb
<div class="col-md-4 col-md-offset-1 col-xs-10 col-xs-offset-1">
  <%= render 'ticker' %>
</div>
<!-- <div class="margin-top"> -->
<div class="col-md-4 col-md-offset-2 col-xs-10 col-xs-offset-1">
  <%= render 'form' %>
</div>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<div class="row">
  <div class="col-xs-8 col-xs-offset-3">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :username %>
      </div>
      <div class="col-sm-6">
        <%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus: true %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :email %>
      </div>
      <div class="col-sm-6">
        <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :password %>
      </div>
      <div class="col-sm-6">
        <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-6">
      <%= f.submit(@user.new_record? ? "Sign up" : "Update your account", class: 'btn btn-primary btn-large') %>
      </div>
    </div>

    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<h1>Edit your account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="regan-container" align="center">
	<h1 align="center">All Users</h1>
	<%= will_paginate %>
	<% @users.each do |user| %>
	<ul class="listing">
		<div class="row">
			<div class="well col-md-4 col-md-offset-4">
				<li><%= link_to gravatar_for(user), user_path(user) %></li>
				<li class="article-title">
					<%= link_to user.username, user_path(user) %>
				</li>
				<% if logged_in? and current_user.admin? %>
				<li><%= link_to "Delete this user", user_path(user), method: :delete,
				data: { confirm: "Are you sure you want to delete the user?" } %></li>
				<% end %>
			</div>
		</div>
	</ul>
	<% end %>
	<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>